### ISSUE TITLE
Parallelized sampling does not work when .py file is executed with IPython or Spyder.

### ISSUE THREAD

**Issue by OssiGalkin** [elfi-dev/elfi#267]
#### Summary:

Parallelized sampling does not work when .py file is executed with IPython or Spyder.

#### Description:
Running parallelized sampling takes forever or produces error if file is executed with Spyder or IPython, but everything works when same lines are copy pasted in IPython.

#### Reproducible Steps:

How to reproduce: Open Spyder, copy following code and save it:

```
import elfi
import numpy as np
from elfi.examples import ma2
seed = 20170530
np.random.seed(seed)

model = ma2.get_model()
elfi.set_client('multiprocessing')

rej = elfi.Rejection(model, 'd', batch_size=10000, seed=20170530)

print ("Starting sampling...")

result = rej.sample(5000, n_sim=int(1e6))
print(result.summary)

# %%
```

Please note that at the end of code there should be cell separator (```# %%```), it does not affect the bug but makes following step with Spyder easier.

#### Reproducing with Spyder (no error message displayed)

Then select first cell and run it (ctrl+enter). Everything should work and after a couple of second result should be printed out.

Then restart the kernel (ctrl+.), just to make sure following steps is executed in 'clean' environment.

Press F5 to execute code. Now it will take very long (or maybe forever) to complete. No error is shown however.

####  Reproducing with iPython (error message is displayed)
Another way to reproduce this error is just run the code from console with IPython, then the error in "Current Output section" is displayed. When code is just copy pasted inside IPython it works just as well as executing cell in Spyder.

#### Current Output:
The code keeps printing following error message in loop, when executed with IPython:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ossig\Google Drive\Koulujutut\ABC\Elfibugi2.py", line 8, in <module>
    elfi.set_client('multiprocessing')
  File "C:\ProgramData\Anaconda3\lib\site-packages\elfi\client.py", line 37, in set_client
    client = m.Client()
  File "C:\ProgramData\Anaconda3\lib\site-packages\elfi\clients\multiprocessing.py", line 30, in __init__
    self.pool = multiprocessing.Pool(processes=num_processes)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 174, in __init__
    self._repopulate_pool()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
    w.start()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

#### Expected Output:

Starting sampling...
bound method Sample.summary of Method: Rejection
Number of samples: 5000
Number of simulations: 1000000
Threshold: 0.0952
Sample means: t1: 0.87, t2: 0.231

#### ELFI Version:
0.7.1

#### Python Version:
3.6.5

#### Operating System:

Windows 10, version 1709, 64 bit
CPU: Intel i7-5600U

**Comment by vuolleko** [comment]
Hi, thanks for reporting this.

I'm unable to reproduce this in iPython on a Mac. I don't have a Windows computer around to test it there. But there seems to be differences in how `multiprocessing` should be used within Windows. Try adding a call to `freeze_support` as instructed in the error message and here:

https://docs.python.org/3.6/library/multiprocessing.html

**Comment by OssiGalkin** [comment]
Yeah, this issue probably comes from differences on how Windows handles multiprocessing because adding freeze_support made my code work. 

Maybe there should be warning to windows users in ELFI docs :)

Code that worked was:
```
from multiprocessing import freeze_support
import elfi
import numpy as np
from elfi.examples import ma2

if __name__ == '__main__':
    freeze_support()

    seed = 20170530
    np.random.seed(seed)

    model = ma2.get_model()
    elfi.set_client('multiprocessing')

    rej = elfi.Rejection(model, 'd', batch_size=10000, seed=20170530)

    print("Starting sampling...")

    result = rej.sample(5000, n_sim=int(1e6))
    print(result.summary)

    # %%

```

**Comment by vuolleko** [comment]
Great, thanks for testing this! I will add this in the notebook on parallelization.
