### ISSUE TITLE
stochastic_optimization call to differential_evolution broken in newer scipy

### ISSUE THREAD

**Issue by johnlees** [elfi-dev/elfi#327]
#### Summary:
After acquiring evidence from the simulator, an error is thrown on the call to scipy's `differential_evolution`.

#### Description:
I think this is possibly an issue due to a change in scipy. If I downgrade to scipy 1.3.1 everything works, but with version >=1.5 (the default installed from conda) I get this error. You could pin the version of scipy in the conda recipe for elfi, but I would suggest updating if possible as doing this is likely to lead to unresolvable environments for many people.

Here is my environment:
```
# Name                    Version                   Build  Channel
appnope                   0.1.0           py36h9f0ad1d_1001    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py36h9f0ad1d_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0    conda-forge
elfi                      0.7.4                      py_2    conda-forge
freetype                  2.10.2               h8da9a1a_0    conda-forge
gpy                       1.9.9            py36h255dfe6_3    conda-forge
graphviz                  2.42.3               h98dfb87_0    conda-forge
ipykernel                 5.3.4            py36h95af2a2_0    conda-forge
ipyparallel               6.3.0            py36h9f0ad1d_0    conda-forge
ipython                   7.16.1           py36h95af2a2_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.17.2           py36h9f0ad1d_0    conda-forge
joblib                    0.16.0                     py_0    conda-forge
jpeg                      9d                   h0b31af3_0    conda-forge
jupyter_client            6.1.6                      py_0    conda-forge
jupyter_core              4.6.3            py36h9f0ad1d_1    conda-forge
kiwisolver                1.2.0            py36h863e41a_0    conda-forge
lcms2                     2.11                 h174193d_0    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libcxx                    10.0.1               h5f48129_0    conda-forge
libffi                    3.2.1             h4a8c4bd_1007    conda-forge
libgfortran               4.0.0                         2    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libllvm9                  9.0.1                h7475705_1    conda-forge
libopenblas               0.3.10          openmp_h63d9170_3    conda-forge
libpng                    1.6.37               hbbe82c9_1    conda-forge
libsodium                 1.0.17               h01d97ff_0    conda-forge
libtiff                   4.1.0                h2ae36a8_6    conda-forge
libwebp-base              1.1.0                h0b31af3_3    conda-forge
llvm-openmp               10.0.1               h28b9765_0    conda-forge
llvmlite                  0.33.0           py36hdce38a9_1    conda-forge
lz4-c                     1.9.2                h4a8c4bd_1    conda-forge
matplotlib                3.3.0                         1    conda-forge
matplotlib-base           3.3.0            py36h534ab7b_1    conda-forge
ncurses                   6.2                  hb1e8313_1    conda-forge
networkx                  1.11                     py36_0    conda-forge
numba                     0.50.1           py36h18adda2_1    conda-forge
numpy                     1.19.0           py36h4a66613_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1g               h0b31af3_0    conda-forge
paramz                    0.9.5                      py_0    conda-forge
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
pexpect                   4.8.0            py36h9f0ad1d_1    conda-forge
pickleshare               0.7.5           py36h9f0ad1d_1001    conda-forge
pillow                    7.2.0            py36h2ae5dfa_1    conda-forge
pip                       20.1.1                     py_1    conda-forge
prompt-toolkit            3.0.5                      py_1    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
python                    3.6.10          h4334963_1011_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
pyzmq                     19.0.1           py36h820b253_0    conda-forge
readline                  8.0                  h0678c8f_2    conda-forge
scikit-learn              0.23.1           py36hef903b7_0    conda-forge
scipy                     1.5.1            py36h1dac7e4_0    conda-forge
setuptools                49.2.0           py36h9f0ad1d_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.32.3               h93121df_1    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tk                        8.6.10               hbbe82c9_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.4            py36h37b9a7d_1    conda-forge
traitlets                 4.3.3            py36h9f0ad1d_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.5                h0b31af3_1    conda-forge
zeromq                    4.3.2                h6de7cb9_2    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
zstd                      1.4.5                h0384e3a_1    conda-forge
```

#### Reproducible Steps:
Run `conda create -n elfi elfi==0.7.4 scipy>=1.5 numpy && conda activate elfi`
Run any model with BOLFI, e.g.:
```
bolfi = elfi.BOLFI(d, batch_size=1, initial_evidence=20, update_interval=10,
                    bounds={'alphaprior1':(0, 5), 'alphaprior2':(0, 5)},
                    acq_noise_var=[0.01, 0.01], seed=1)

post = bolfi.fit(n_evidence=400)
```

#### Current Output:
After the evidence acquisition is complete:
```
Progress: |██████████████████████████████████████████████████| 100.0% Complete
Traceback (most recent call last):
  File "ELFI.simulator.py", line 61, in <module>
    post = bolfi.fit(n_evidence=40)
  File "/Users/jlees/miniconda3/envs/elfi/lib/python3.6/site-packages/elfi/methods/parameter_inference.py", line 1191, in fit
    self.infer(n_evidence, bar=bar)
  File "/Users/jlees/miniconda3/envs/elfi/lib/python3.6/site-packages/elfi/methods/parameter_inference.py", line 276, in infer
    return self.extract_result()
  File "/Users/jlees/miniconda3/envs/elfi/lib/python3.6/site-packages/elfi/methods/parameter_inference.py", line 953, in extract_result
    self.target_model.predict_mean, self.target_model.bounds, seed=self.seed)
  File "/Users/jlees/miniconda3/envs/elfi/lib/python3.6/site-packages/elfi/methods/bo/utils.py", line 32, in stochastic_optimization
    func=fun, bounds=bounds, maxiter=maxiter, polish=polish, init='latinhypercube', seed=seed)
  File "/Users/jlees/miniconda3/envs/elfi/lib/python3.6/site-packages/scipy/optimize/_differentialevolution.py", line 308, in differential_evolution
    ret = solver.solve()
  File "/Users/jlees/miniconda3/envs/elfi/lib/python3.6/site-packages/scipy/optimize/_differentialevolution.py", line 814, in solve
    constraints=self.constraints)
  File "/Users/jlees/miniconda3/envs/elfi/lib/python3.6/site-packages/scipy/optimize/_minimize.py", line 618, in minimize
    callback=callback, **options)
  File "/Users/jlees/miniconda3/envs/elfi/lib/python3.6/site-packages/scipy/optimize/lbfgsb.py", line 308, in _minimize_lbfgsb
    finite_diff_rel_step=finite_diff_rel_step)
  File "/Users/jlees/miniconda3/envs/elfi/lib/python3.6/site-packages/scipy/optimize/optimize.py", line 262, in _prepare_scalar_function
    finite_diff_rel_step, bounds, epsilon=epsilon)
  File "/Users/jlees/miniconda3/envs/elfi/lib/python3.6/site-packages/scipy/optimize/_differentiable_functions.py", line 95, in __init__
    self._update_grad()
  File "/Users/jlees/miniconda3/envs/elfi/lib/python3.6/site-packages/scipy/optimize/_differentiable_functions.py", line 171, in _update_grad
    self._update_grad_impl()
  File "/Users/jlees/miniconda3/envs/elfi/lib/python3.6/site-packages/scipy/optimize/_differentiable_functions.py", line 92, in update_grad
    **finite_diff_options)
  File "/Users/jlees/miniconda3/envs/elfi/lib/python3.6/site-packages/scipy/optimize/_numdiff.py", line 388, in approx_derivative
    raise ValueError("`f0` passed has more than 1 dimension.")
ValueError: `f0` passed has more than 1 dimension.
```

#### Expected Output:
Gives me a correct bolfi object, with a lower version of scipy

#### ELFI Version:
0.7.4
#### Python Version:
3.6
#### Operating System:
OS X 10.15

**Comment by hpesonen** [comment]
Thanks for pointing this out! Fixed with #328
