### ISSUE TITLE
import elfi fails

### ISSUE THREAD

**Issue by hpesonen** [elfi-dev/elfi#464]
#### Summary:
`import elfi` fails - caused by missing `__init__.py` in elfi/methods/inference/bsl 

#### Description:
```
Traceback (most recent call last):
  File "MA2_run.py", line 1, in <module>
    import elfi
  File "/opt/anaconda3/envs/test_elfi_085/lib/python3.8/site-packages/elfi/__init__.py", line 19, in <module>
    from elfi.methods.inference.bsl import *
  File "/opt/anaconda3/envs/test_elfi_085/lib/python3.8/site-packages/elfi/methods/inference/bsl.py", line 10, in <module>
    from elfi.methods.bsl.pdf_methods import gaussian_syn_likelihood
ModuleNotFoundError: No module named 'elfi.methods.bsl'
```

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

**Comment by hpesonen** [comment]
Fixed in #465
